### PR TITLE
fixed vertical slider example

### PR DESCRIPTION
**Pull request by GregorGabric**

### CODE REVIEW

**Review by IHIutch — APPROVED** [review]
Thanks @GregorGabric, some of the changes were a little more than necessary so I made some additional adjustments based on your changes. 

Please do make sure to provide a justification for your PR in the future. It makes it easier to understand the original problem and your proposed solution.

**Comment by GregorGabric** [comment]
Hey, apologies for not giving the clarification, will do so in the future.

As for the height on the SliderTrack, doesn't it make more sense for the parent element to have the specified height? 

Height is given to the parent in this example from  [react aria](https://react-spectrum.adobe.com/react-aria/Slider.html#visual-options)

Kind regards

**Comment by IHIutch** [comment]
Good thought. In that example, the height must be given to the outer most parent because it is what can accept style props. With that contrived example, there would be no way to adjust height, except to change the CSS. In our case, we do have access to `SliderTrack` and can style it directly. Because of this, we only have to worry about the relationship of 2 elements, rather than 3. Further, other elements can exist within `Slider` which could affect it's overall height, like `SliderOutput`.

**Comment by GregorGabric** [comment]
May I help with anything else?

**Comment by IHIutch** [comment]
You're welcome to contribute as you like. If you find any other issues or want to add a new example, feel free to suggest something. It might be easier to add issues first, as a way to ideate and focus, then submit a PR against the issue(s)

**Pull request merged**
